DROP DATABASE IF EXISTS betting_db;
CREATE DATABASE betting_db;

\c betting_db;

DROP TABLE IF EXISTS players;

CREATE TABLE players (
	player_id INT GENERATED BY DEFAULT AS IDENTITY,
	player_name VARCHAR(255) NOT NULL,
	PRIMARY KEY(player_id)
);

DROP TABLE IF EXISTS tournaments;

CREATE TABLE tournaments (
	tournament_id VARCHAR(20),
	tournament_name VARCHAR(255) NOT NULL,
	PRIMARY KEY(tournament_id)
);

DROP TABLE IF EXISTS teams;

CREATE TABLE teams (
	team_id VARCHAR(20),
	team_name VARCHAR(255) NOT NULL,
	PRIMARY KEY(team_id)
);


DROP TABLE IF EXISTS matches;

CREATE TABLE matches (
	match_id VARCHAR(50),
	tournament_id VARCHAR(20) NOT NULL,
	team1_id VARCHAR(20) NOT NULL,
	team2_id VARCHAR(20) NOT NULL,
	team1_goals INT NOT NULL,
	team2_goals INT NOT NULL,
	matchresult VARCHAR(1) NOT NULL,
	PRIMARY KEY(match_id)
);


DROP TABLE IF EXISTS betting_picks;

CREATE TABLE betting_picks (
	betting_picks_collection_id VARCHAR(12),
	betting_pick_id VARCHAR(17),
	player_id INT,
	match_id VARCHAR(50),
	matchresult VARCHAR(1) NOT NULL,
	team1_goals INT ,
	team2_goals INT ,
	PRIMARY KEY(betting_picks_collection_id,betting_pick_id,player_id),
	FOREIGN KEY(match_id) REFERENCES matches (match_id) ON DELETE CASCADE,
	FOREIGN KEY(player_id) REFERENCES players (player_id)
);

